### ISSUE TITLE
IR 3.6.10 Erratic behaviour when zooming

### ISSUE THREAD

**Issue by SebastianGG** [luoliyan/incremental-reading-for-anki#25] opened 2017-09-20 17:23 UTC
Zooming doesn't work at first on the main screen or after opening a deck (I mean the screen where you see the deck's name, new/learning/review count and "Study now" button). Once I start actually doing reviews, though, zoom starts working not just on the reviewing screen, but also in both screens previously mentioned. It doesn't work on the stats screen, but I guess that could be how it's supposed to work?

I use IR 3.6.10 on Anki 2.0.47 on Windows 10.

**Comment by luoliyan** [comment] 2017-09-21 01:37
That sounds like how I intended for it to work. For the deck screen and study screen, you can set the zoom percentage in the zoom settings tab. I'll have a think about adding shortcuts to those screens.

**Comment by luoliyan** [comment] 2017-10-18 14:55
Sorry, I misunderstood. What you describe is _not_, in fact, the intended behaviour, and it has now been fixed in the v4 development code, and will be fixed soon in v3 as well.

Thanks for your report.

**Closed by luoliyan** 2017-10-18 14:55 UTC
Labels: bug
